    <!--
    See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
    -->

    <?php if ($this->pageCount): ?>
    <div class="paginationControl">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url(array('strona' => $this->previous)); ?>">
        &lt; Poprzednia
      </a> |
    <?php else: ?>
      <span class="disabled">&lt; Poprzednia</span> |
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <a href="<?php echo $this->url(array('strona' => $page)); ?>">
            <?php echo $page; ?>
        </a> |
      <?php else: ?>
        <?php echo $page; ?> |
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url(array('strona' => $this->next)); ?>">
        Następna &gt;
      </a>
    <?php else: ?>
      <span class="disabled">Następna &gt;</span>
    <?php endif; ?>
    </div>
    <?php endif; ?>