<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Zero9gravity Admin</title>
	
	<link type="text/css" href="<?=$this->baseUrl('admin/css/main.css')?>" rel="stylesheet" />
	<link type="text/css" href="<?=$this->baseUrl('admin/css/colors/dark_blue.css')?>" rel="stylesheet" />
	<link type="text/css" href="<?=$this->baseUrl('admin/css/superfish.css')?>" rel="stylesheet" />
	<link type="text/css" href="<?=$this->baseUrl('admin/jstree_themes/default/style.css')?>" rel="stylesheet" />

	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-1.4.2.min.js')?>"></script>    
	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-ui-1.8.1.custom.min.js')?>"></script>

	<script type="text/javascript" src="<?=$this->baseUrl('js/ckeditor/ckeditor.js')?>"></script> 
	<script type="text/javascript" src="<?=$this->baseUrl('js/ckfinder/ckfinder.js')?>"></script> 
	<script type="text/javascript" src="<?=$this->baseUrl('js/ckeditor/adapters/jquery.js')?>"></script>

	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.hoverIntent.minified.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/superfish.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.tools.min.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.simplemodal.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.notifyBar.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.tipsy.js')?>"></script>
	<!--<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.validate.js')?>"></script>-->
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/enhance.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/excanvas.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/visualize.jQuery.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jQuery.collapsible.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.autoSuggest.packed.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.jstree.js')?>"></script>
	
</head>

<body>
		<?=$this->layout()->content?>
</body>
</html>