<div class="innerdiv clear">
	<!-- Tabs -->
	<h2 class="head-alt-white">Ludzie</h2>
	<ul class="tabs">
		<li><a class="current" href="<?=$this->baseUrl('cms/users')?>">Lista</a></li>
		<li><a href="<?=$this->baseUrl('cms/users/add')?>">Dodaj nowego</a></li>
	</ul>
	<div class="innercontent">
		<!-- tab "panes" -->
		<div class="panes">
			<div style="display: block;">
				<table id="users-list" class="full"></table>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
<!--
	$('#users-list').zGrid({
		url: '/rest/users',
		pageTotal: <?=$this->pageTotal?>,
		pageLimit: <?=$this->pageLimit?>,
		checkboxes: true,
		controls: true,
		paginator: true,
		pageTag: 'page',
		sortable: true,
		sortTag: 'sort',
		cols: [{
			label: 'Imię',
			id: 'name',
			type: 'head',
			sortable: true
		},{
			label: 'Nazwisko',
			id: 'surname',
			type: 'head',
			sortable: true
		},{
			label: 'Email',
			id: 'email',
			type: 'string',
			sortable: true
		},{
			label: 'Telefon',
			id: 'phone',
			type: 'string',
			sortable: true
		},{
			label: 'Agent',
			id: 'agent',
			type: 'img',
			sortable: true
		}],
		bulk: [{
			label: 'Usuń',
			action: 'delete'
		}],
		onLoad: function(){
			$('.delete-btn').click( function(e){
				e.stopPropagation();
				confirm( 'usuwamy?', function() {
					deleteUser(e.currentTarget.name);
				});
				return false;
			});
		},
		onBulk: function( action, selected ){
			if( action == 'delete' ) {
				confirm( 'usuwamy?', function() {
					selected.each(function(i, chk) {
						deleteUser(chk.value);
					});
				});
			}
		}
	});

	function deleteUser(id) {
		var result = client['user.delete'](id);
		if(client.error) {
			showError('Usunięcie nie powiódło się :(');
		} else {
			//window.location.reload();
			$('#users-list').zGridDeleteRow(id);
			showSuccess(result);
		}
	}
//-->
</script>