<div id="login">
	<h2 class="head-alt">Panel Administracyjny - Logowanie</h2>
	<div class="panes">
		<div>
			<form id="login-form" name="login" action="#login" method="post">
				<fieldset>
					<legend>Podaj swój email i hasło</legend>
					<label for="iLogin">Email:</label><input id="iLogin" name="login" type="text" />
					<label for="iPassword">Hasło:</label><input id="iPassword" name="password" type="password" />
					<br/>
					<label class="checkbox"><input type="checkbox" name="rememberme"/> zapamietaj&nbsp;mnie&nbsp;w&nbsp;tej&nbsp;przeglądarce</label>
					<input class="button" type="submit" value="Log in!" /><div class="clear"></div>
				</fieldset>
			</form>
			<div id="validation-summary"></div>
		</div>
	</div>
</div>
<script type="text/javascript">
$('#iLogin').focus();
</script>