<h1>Jak do nas trafić</h1>
<?php echo $this->pages(); ?>
<div id="map_canvas"></div>
<script type="text/javascript"
		src="http://maps.google.com/maps/api/js?sensor=false">
</script>
<script type="text/javascript">
	function iniMap() {
		var latlng = new google.maps.LatLng(54.4409, 18.5606);
		var center = new google.maps.LatLng(54.4417, 18.5606);
		var myOptions = {
			zoom: 16,
			center: center,
			mapTypeId: google.maps.MapTypeId.ROADMAP
		};
		var map = new google.maps.Map(document.getElementById("map_canvas"),
		myOptions);
		// Create one InfoWindow to open when a marker is clicked.
		var infowindow = new google.maps.InfoWindow({
			content: '<h3>Jodłowski. Nieruchomości Pomorza Gdańskiego</h3>Aleja Niepodległości 767<br/>Sopot, Polska<br/>Telefon: 58 550 30 80',
			disableAutoPan: true
		});
		var marker = new google.maps.Marker({
			position: latlng,
			map: map,
			//animation: google.maps.Animation.BOUNCE,
			title:"Nieruchomości Pomorza Gdańskiego"
		});
		
		google.maps.event.addListener(marker, 'click', function() {
			infowindow.open(map,marker);
		});

		infowindow.open(map,marker);
	}


	$(function() {
		iniMap();
	})
</script>
<a href="http://maps.google.com/maps?f=q&source=s_q&hl=pl&geocode=&q=npg.pl&sspn=0.007762,0.026157&ie=UTF8&hq=npg.pl&hnear=&ll=54.441559,18.562925&spn=0.007762,0.026157&z=16&iwloc=A" target="_blank" title="Pokaż mapę w nowym oknie">Pokaż mapę w nowym oknie</a> | 
<a href="http://maps.google.com/maps?f=d&source=s_d&saddr=&daddr=Aleja+Niepodleg%C5%82o%C5%9Bci+767,+Sopot,+Polska+(Jod%C5%82owski.+Nieruchomo%C5%9Bci+Pomorza+Gda%C5%84skiego)&hl=pl&geocode=Cc45lJseMdVPFTuzPgMdzTUbASEN2fHoPzIhrw&mra=ls&sll=54.441722,18.562925&sspn=0.007687,0.026157&ie=UTF8&ll=54.441559,18.562925&spn=0.007999,0.026157&z=16" target="_blank" title="Wskazówki dojazdu">Wskazówki dojazdu</a>