<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-easing-1.3.pack.js');?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-easing-compatibility.1.2.pack.js');?>"></script>
<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.kwicks-1.5.1.pack.js');?>"></script>

<div class="jimgMenu">
  <ul>
    <li id="domy"><a href="<?=$this->baseUrl('domy/sprzedaz');?>">Domy</a></li>
    <li id="mieszkania"><a href="<?=$this->baseUrl('mieszkania/sprzedaz');?>">Mieszkania</a></li>
    <li id="obiekty"><a href="<?=$this->baseUrl('obiekty/sprzedaz');?>">Obiekty</a></li>
  </ul>
</div>

<script type="text/javascript">
$().ready(function() {
	$('.jimgMenu ul').kwicks({max: 700, duration: 500, easing: 'easeOutQuad', complete: 'callback'});
});
</script>